[normal]
log[] = "screen"
color = "COLOR_REGULAR"
log[] = "max"
emoji = "green circle"

[event]
log[] = "screen"
color = "COLOR_EVENT"
log[] = "file"
reduction = "V"
log[] = "max"
emoji = "green circle"


[warning]
log[] = "screen"
color = "COLOR_WARNING"
log[] = "file"
reduction = "W"
log[] = "max"
emoji = "orange circle"

[service]
log[] = "screen"
color = "COLOR_INFO"
log[] = "file"
reduction = "S"
log[] = "max"
emoji = "sparkles"

[incident]
log[] = "screen"
color = "COLOR_EVENT"
log[] = "file"
reduction = "I"
log[] = "max"
emoji = "violet circle"

[error]
log[] = "screen"
color = "COLOR_DANGER"
log[] = "file"
reduction = "E"
log[] = "max"
emoji = "red circle"

[alert]
log[] = "screen"
color = "COLOR_DANGER"
log[] = "file"
reduction = "A"
log[] = "max"
log[] = "database"
emoji = "red exclamation"

[fatal]
log[] = "screen"
color = "COLOR_DANGER"
log[] = "file"
reduction = "F"
log[] = "max"
emoji = "stop sign"
log[] = "database"

;db[host] = ""
;db[name] = ""
;db[user] = ""
;db[table] = ""
;db[port] = ""
;db[pass] = ""
;db[days_store] = 30